### ISSUE TITLE
VBGclearBreakpints won't work

### ISSUE THREAD

**Issue by kaldown** [idanarye/vim-vebugger#54]
VBGclearBreakpints won't clear breakpoints
![2018-03-09--15 58 03_846x248_scrot](https://user-images.githubusercontent.com/3754017/37208558-ce0451d0-23b2-11e8-8808-d5bb2a7cb003.png)

```
# vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 30 2017 18:21:38)


```

**Comment by idanarye** [comment]
OK, I checked, and there is a bug here - I just want to quickly verify it's the same bug you are encountering:

* When you run `:VBGclearBreakpints`, **only one** breakpoint gets removed.
* Afterwards, every time you run a `:VBGstepXXX` command - another breakpoint gets removed, until all of them are gone.

If you encounter a similar behavior, then the breakpoints do get removed - it's just their `sign`s that stay, because apparently I need to remove them one by one...

No idea how I've missed this until now... this behavior of Vim does not seem to be new...

**Comment by IngoMeyer441** [comment]
I also did a quick test and for me it is not only a visual problem. `VBGclearBreakpoints` clears one breakpoint and the other break points only get cleared after `VBGstep` commands (verified with the Vebugger Terminal window).
